### ISSUE TITLE
PPL ZPL labels

### ISSUE THREAD

**Issue by samuelszabo** [Salamek/PplMyApi#25]
Did you ever used ZPL labels?
https://pastebin.com/dpd70REX -> http://labelary.com/viewer.html

How to contribute? Extend Label class, or create new ZplLabel class?

**Comment by Salamek** [comment]
@samuelszabo Hi, no i never used ZPL... but i'd like to have it implemented!

I think creating new ZplLabel class would be a best approach:

1 . Create Interface ILabel with generateLabels, generateLabelFull, generateLabelQuarter methods
2. Rename current Label class to PdfLabel and implement ILabel
3. Create compability class Label extending from PdfLabel + some user deprecated warning when used
4. Create ZplLabel class implementing ILabel, if some methods from ILabel are not appropriate for ZplLabel, just put `throw new NotImplementedException();` in there...

What do you think ?

**Comment by vaclavvanik** [comment]
ZPL is directly in format 4x5". It does not have options like 4 labels per A4 page.

**Comment by Salamek** [comment]
@samuelszabo released in v1.2.1, THX
