### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by MiroslavReiss** [Salamek/PplMyApi#3]
Login doesn't work? "Fatal error: Uncaught Salamek\PplMyApi\Exception\SecurityException: Pokus o přihlášení byl neúspěšný, zkontrolujte uživatelské jméno a heslo"

**Comment by Salamek** [comment]
@MiroslavReiss it should work, we are using this library in live env and works ok

**Comment by MiroslavReiss** [comment]
That's weird, I don't know where can be mistake. Well, thanks for reply anyway. By the way just for sure, login is the same for klient.ppl.cz, right?

**Comment by Salamek** [comment]
@MiroslavReiss no... you must request MyApi creditials from PPL IT

**Comment by MiroslavReiss** [comment]
That awkward moment... my bad, thanks again.
