### ISSUE TITLE
Neprechádza mi request

### ISSUE THREAD

**Issue by triblavina** [Salamek/PplMyApi#39]
Podľa pokynov chcem pridať balík pomocou metódy createPackages. Na mojej strane vyzerá všetko OK, pri výpise mi však balík nenájde a tým pádom request zrejme neprechádza

výber kódu
```
$recipient = new Salamek\PplMyApi\Model\Recipient('Olomouc', 'Adam Schubert', 'My Address', '77900', 'adam@example.com', '+420123456789', 'http://www.salamek.cz', Country::CZ, 'My Compamy a.s.');
$package = new Salamek\PplMyApi\Model\Package($packageNumber, Product::PPL_PARCEL_CZ_PRIVATE, $weight, 'Testovaci balik', Depo::CODE_09, $recipient);
$pplMyApi->createPackages([$package]);
```
nevyskočí mi žiadna chyba. testovacie údaje mám z podpory. uvádzam request aj response
```

REQUEST HEADERS:
POST /MyAPI.svc HTTP/1.1
Host: myapi.ppl.cz
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.1.22
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://myapi.ppl.cz/v1/IMyApi2/CreatePackages"
Content-Length: 1541

REQUEST BODY:

RUFBQUFJakpFWllfdHBKbmxhTzlsVDQ0TFJqWW90X1hrSzh2MWxBV1hrQnVnYjl1cGU4cnpDdlBSOFpwX1hMd0JheEFnaURwS0wzRTVwM0VLLTdlOTZvZEVINXJxTkhrZDRTSTlURzZYazZEdEljdlVrSFQ5T2tQUXA2Q3V5T2c5dl9ZYXB2cy1CcWQxQ24wRnlIOEVZWXluMmc0NjBHa21UM2FBMVJlSDJiMkh6N2M4YzVtbEk0NThjUzlhZzBWdlplckdONkxZakxKUVlEWWh0ckI2QjlSSjV6ZEY0cFU4cFJpX2tSTHNFdU9jY3BvSmVtclByZmV2X3lmTjc0ay1YSUZydzI=4005058832913Testovaci balik09Olomouchttp://www.salamek.czCZadam@example.comAdam SchubertMy Compamy a.s.+420123456789My Address77900


RESPONSE HEADERS:
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Length: 763
Content-Type: text/xml; charset=utf-8
Server: 
Strict-Transport-Security: max-age=31536000
X-Frame-Options: DENY
X-Powered-By: 
X-Powered-By: 
Date: Mon, 01 Oct 2018 20:13:50 GMT


RESPONSE BODY:
RUFBQUFCY3FWNkg3cTBka0EtSU9zTTZmN2Fmcmxvd25YX2szTFNNNHd1QTZaQ0lZaEp4Q2xBRVU4MTJWT0xDSlJ2ejFGRXk1Zkd3RC1HVWkwRTZMcTE2d1VNUV80c05DSk1scHFOdlRnakpTUFExSEhzc05UT2NkT1oyekw0YlVXd3JTUk1QaGswMS05VXVVR0VTOWh5d1IxSFRhdEhoSm04a2xQTVhsY1VBS0s1TFpMWnBTZG9KNlNuQmRjNWxzeFZlV242cDFfVW5kb2FHWlZ0OVd3SUtCd2VmODVBVENMdF9ZQU5oUkNMSVRSMllHWnFpdThIdDdzTDBkZG9mcy1WTm5aQTI=040050588329)
```

viete prosím poradiť čo robím zle?

**Comment by Salamek** [comment]
@triblavina 
> pri výpise mi však balík nenájde
Jak provadis vypis baliku ?

Pripadne si dumpni (treba pomoci print_r($result);) $result v createPackages jestli tam neni nejake info... (i kdyz mam pocit ze selhany request hazi Exception)

**Comment by triblavina** [comment]
Ako ono vyzerá, že to prechádza, vracia to kód 0. Všetko by malo byť OK
`stdClass Object ( [CreatePackagesResult] => stdClass Object ( [AuthToken] => RUFBQUFNS0sxaS1jOHlmeFZoRW5XcFE5UGRFNy1mTFRGYi1HZlhZY0VGYmNoeGRQbGV1Vzg1dEtfSHdWMXBjZHFtYkxXTmpQcV9oRVpZY09DVXAtaEdHS0RHQUlwNU10QWJYX0FXblJZazhHYlpuQ2Y1TkdiTjdvZ3RyT2t5SmhKUTBoeDZRQVdiSHZwVGJLU2hmN1JxaGprNVpQVURJd1NFMjR6V29VX2FBbjF4Tk1MbFhlVThkd015TE5QZ0lHZVJNeDk1UTk2VldUNEE2OGt5WHo4ZnU1dHFxeVpyeDdseHhVelc5WDEzWm9ncHNwWU4yMHpHdzMxTmdaRjEtbFlOWnRzdzI= [ResultData] => stdClass Object ( [ItemResult] => stdClass Object ( [Code] => 0 [ItemKey] => 40050588329 [Message] => ) ) ) )`

ALE vo výpise sa to číslo nenachádza.
```
$date = new DateTime(2018-10-01);
$date2 = new DateTime(2018-10-02);
$pplMyApi = new Salamek\PplMyApi\Api($username, $password, $customerId);
$result = $pplMyApi->getPackages(null, $date, $date2, []);
echo '<pre>' , var_dump($result) , '</pre>';
```
mám za to, že getPackages by mi to malo vrátiť aj package, ktorý som práve pridal pomocou createPackage.

**Comment by Salamek** [comment]
@triblavina 
Tak web PPL o tom balik vi viz: 
https://www.ppl.cz/main2.aspx?cls=Package&idSearch=40050588329

Ted jen zjistit proc getPackages ti nic nevraci...
Zase si zkus dumpnout `$result` v `getPackages` pripadne si pohrat s parametry te metody, ja to bohuzel nemuzu otestovat protoze nemam zadne validni testovaci pristupy k PPL MyApi k dispozici...

**Comment by JanGalek** [comment]
tuším že package nevrací, možná mi mohl ověřit @unzeitigm ;)

**Comment by triblavina** [comment]
@Salamek zmenil som ID balíka na ďalšie v poradí, a všetko prejde OK a aj mi ho ukáže vo výpise. neviem kde bol problém, no už nie je. filtruje mi to aj podľa dátumu aj ID :)

@JanGalek getPackages aby nevracal package? to by bol aký podlý ťah od tvorcu API? :D ale už všetko OK. 

pre ostatných môžem potvrdiť funkčnosť, podľa pokynov som to rozchodil a spojenie s API funguje

**Comment by Salamek** [comment]
@triblavina takze issue muzeme zavrit ? :smile_cat:

**Comment by triblavina** [comment]
@Salamek áno
