### ISSUE TITLE
SSL cert on *.ppl.cz is valid!

### ISSUE THREAD

**Issue by Salamek** [Salamek/PplMyApi#4]
SSL cert on *.ppl.cz is valid! remove hack from Api.php
https://github.com/Salamek/PplMyApi/blob/master/src/Api.php#L127
to improve security

**Comment by LadisCZ** [comment]
Hi,

https://github.com/Salamek/PplMyApi/blob/master/src/Api.php#L292

The column name for Order Reference ID is "**OrdRefId**", not "OrdRefID" (https://myapi.ppl.cz/MyAPI.svc?singleWsdl).

The current field name results in a response "OrdRefId is a mandatory field".
