### ISSUE TITLE
Allow to set the first label position on page when generating labels using quarter decomposition.

### ISSUE THREAD

**Issue by samotlark** [Salamek/PplMyApi#42]
I would like to be able to set first label position on page when generating labels using quarter decomposition.

When you print only one label, use it and later on you would like to reuse the rest of the paper, you have to start printing labels from 2nd, 3rd or 4th position on the paper. It would be useful to allow configuration of the starting position in function call.

Currently it's hardcoded like that:
`$quarterPosition = LabelPosition::TOP_LEFT;`

It would be useful to move it to method parameter with default value.

**Comment by Salamek** [comment]
@samotlark feel free to create a tested PR
