### ISSUE TITLE
Chyba při generování barcode?

### ISSUE THREAD

**Issue by lamas525** [Salamek/PplMyApi#45]
Zdravím přátelé,

Integruji do svého eshopu PPL a chtěl bych využít tohle řešení ke generování a tisknutí štítků k objednávkám. Úspěšně sem tedy prošel nastavením všeho potřebného až sem se dostal k samotnému generování ZPL a PDF souboru obsahující objednávku. Vše se povedlo v pořádku jediný problém mám že když přečtu barcode (at už ten example co je v testu nebo ikdyž si udělám vlastní PDF , ZPL) tak tam mám vždy nakonci nějakou číslici navíc. Zkoušel sem čtečku přes mobil zkoušel sem i kod vyříznout a zkoušel to protáhnout barcode readery online a vždy tam mám číslo navíc. 
Zde screenshot:
https://imgur.com/a/t6Ilg6W
číslo té objednávky by mělo být 40950000196 
Nevím proč tam je ta nula navíc. Můžete mi prosím případně někdo říct kde je chyba případně ověřit že se nejedná o bug? 

Děkuji moc jinak skvělá práce.

**Comment by vaclavvanik** [comment]
Ahoj, to je kontrolní číslo, které se nerenderuje v těch číslíčkách pod barcode. Je to tak v pořádku.

**Comment by lamas525** [comment]
Ahoj ještě mám jeden dotaz. Všiml sem si že PPL štítky které používáme dnes na balících (exportujeme si data do jejich systému pomocí CSV) jsou trochu jiné. Formát je trochu jiný a barcody jsou tam dva. Proto mi trochu neleze do hlavy proč tenhle formát je takhle "jiný",.
Děkuji za odpovědi. Upřímně mi celý ten sestém přijde takový podivný takže za objasnění budu velice rád
https://imgur.com/a/yMTf1GP

**Comment by Salamek** [comment]
@lamas525 Hmm je mozne ze PPL zmenilo vzhled svych stitku ale zaroven stale podporuje stary vzhled... Od doby co jsem vytrvoril prvni PDF stitek pro tuto knihovnu uz to budou nejake ty roky a jako sablona byl pouzity official stitek primo od PPL, mozna by bylo dobre se dotazat vaseho kontaktu v PPL jake jsou jejich "plany" a WTH...

**Comment by lamas525** [comment]
Zdravím dnes sem s PPL v kontaktu byl. Bylo nám potvrzeno že ta šablona která je použita je v pořádku.. Věřím tedy že nakonec vše bude v pohodě. Díky za tvoji skvělou práci. :)

**Comment by lamas525** [comment]
Dnes mi došli ještě podrpobnosti k integraci. Podle zpráv z PPL od června mají přejít na nový systém štítků.

**Comment by vaclavvanik** [comment]
Imho bude i metoda pro renderování štítků přes API. Což by bylo fajn.

**Comment by lamas525** [comment]
Mám k tomu kdyžtak i nejnovější dokumentaci aktualizovanou 2020 kdybyste o ni měli zájem mohu asi poskytnout .

**Comment by vaclavvanik** [comment]
Mám ji taky. Díky za nabídku :-)

**Comment by Salamek** [comment]
Care to share? :smile_cat: 
Uz je v te nove implementaci vyreseno automaticke pridelovani cisla baliku pri zakladani baliku? nebo je to furt stejna pakarna kdy si clovek musi vyzadat rozsah pro kazdych 200 baliku a drzet to u sebe v DB jak vocas...

`<rejpnuti>`A z tech stitku generovanych na strane PPL bych se moc neradoval, co mam (stare) interni info o urovni jejich IT a "schopnosti" dodavatele IS kteri v teto kombinaci byli schopni odstavit cele PPL na dva mesice... nedokazu si predstavit jak tito experti daji efektivne do kupy generovani PDF... ZPL by mohli ~zvladnout to je jen text... i MyApi ma hromadu nedostatku a jde videt ze rozhrani navrhoval nekdo kdo si k tvorbe API moc necuchl...(i kdyz videl jsem horsi o tom zadna). No budu doufat ze nova verze se zbavuje vsech mych pripominek z komentare v https://github.com/Salamek/PplMyApi/blob/master/src/Api.php (a to je cca 40% toho co jsem nasel, pak me to proste prestalo bavit zapisovat) `</rejpnuti>`

_PS: No a na konec bych chtel rict ze momentalne nemam zadneho placeneho zakaznika pouzivajci tuto knihovnu, takze pokud bude treba udelat nejake vetsi zmeny mou osobou, bude to muset nekdo zadotovat/poslat PR s testy ktere jen schvalim etc. nemam totiz problem tuto knihovnu udrzovat zadarmo, ale delat na ni nejake vetsi prace (napr. predelani stylu stitku etc.) zadarmo jen tak delat nebudu :)  Ne ze bych byl tak moc na penize, jen proste na praci zadarmo pro OSS neni cas..._
