### ISSUE TITLE
Could not load 

### ISSUE THREAD

**Issue by Rukes** [Salamek/PplMyApi#46]
Zdravím,

chci se zeptat proč po dvou dnes testování mi najednou API hází tento error? (do API contructoru jsem si jen přidal error message). Na kód sem od včera nijak nesahal, najednou toto.

`Failed to build soap client: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https:\/\/myapi.ppl.cz\/MyApi.svc?singleWsdl' : failed to load external entity \"https:\/\/myapi.ppl.cz\/MyApi.svc?singleWsdl\"\n`

Díky, Rukes :)

**Comment by Salamek** [comment]
@Rukes 
Ahoj, bude to tim ze patlalove z PPL IT neumi udrzovat sve systemy bez odstavky see https://myapi.ppl.cz/MyApi.svc?singleWsdl

PS: Udelat to zakaznikovi na hodinu ja, tak prijede ke me domu a zlame mi obe nohy... holt ale neberu miliony takze si to nemuzu dovolit :)

**Comment by Rukes** [comment]
Aha, moc se omlouvám, nenapadlo me ze bude odstavka...

Děkuji moc

**Comment by Salamek** [comment]
Jako sestrelit vsechny svoje webove sluzby do 6:00, 24.5.2020 to uz je fakt jinej level :-D

**Comment by Rukes** [comment]
Já pred tydnem cetl že bude ostavka, ale nepsali tam nic o tom ze "ne, nepojede ani API"

**Comment by Salamek** [comment]
No zda se ze nejede vubec nic... nechapu co tam delaji... clovek by cekal ze takova firma bude mit svoje systemy na nejakem HA Clusteru spravovany nejakym profikem. Migrace sluzeb provedu presmerovanim provozu ze stare instance na novou otestovanou a pripravenou v radu desitek sekund... ale co za uroven IT bych chtel po ceske firme ze :) Doufejme ze to fakt stihnou do specifikovaneho terminu a nebude to jako naposled kdy byli mimo provoz skoro 14dni :smile:

**Comment by Rukes** [comment]
S PPL jsem zacatecnim, ale 14 dni zni dost nepredstavitelne :D uprimne me dost zaujalo uz to, ze kdyz sem si napsal o API a potom o udaje tak po me nikdo nechtel zadne overeni ze pro danou firmu opravdu pracuji :D

asi tyden sem se (s prominutim) sral se SOAPem a vubec mi to neslo, diky ti ze sem nasel tvou API, s tim se da perfektne pracovat, dobra prace! :)

**Comment by Salamek** [comment]
PPL je super prepravce, ale jejich IT je nic moc no :) Tak at slouzi!
