### ISSUE TITLE
PackageSet

### ISSUE THREAD

**Issue by kibkib** [Salamek/PplMyApi#51]
pri createPackages sa neodesila PackageSet, tedy hodnoty packageCount a packagePosition

jiz se to resilo v issue #38 , tehdy to nebylo povinne, nyni je tato polozka PPL vyzadovana

**Comment by hary28** [comment]
V tomto commitu https://github.com/MRzr/PplMyApi/commit/6301fc0787d98494cc4a13faf7f08fcaa4918458 to někdo nějakým způsobem vyřešil, ale chtělo by to projít, zkontrolovat a udělat pull request. :-)

**Comment by AlexKratky** [comment]
https://github.com/Salamek/PplMyApi/pull/58

**Comment by Salamek** [comment]
Closed by https://github.com/Salamek/PplMyApi/commit/b38f2d6abee2eee46e042aabb661afe3dc99321c
