### ISSUE TITLE
Typo in createPickupOrders

### ISSUE THREAD

**Issue by xmalikm** [Salamek/PplMyApi#54]
I noticed there's a minor typo in the createPickupOrders method within the Api.php class.
The soap request parameter 'MyApiPickUpOrderIn' should be 'MyApiPickupOrderIn' based on the official PPL myApi documentation.
Would it be possible to fix it ?

[myAPI_Dokumentace_v2.6.14072020.pdf](https://github.com/Salamek/PplMyApi/files/6240219/myAPI_Dokumentace_v2.6.14072020.pdf)

**Comment by Salamek** [comment]
@xmalikm umm i don't see any typo, there is a 'MyApiPickUpOrderIn' and that PDF mentions 'MyApiPickUpOrderIn' so em?

**Comment by xmalikm** [comment]
The problem is with the uppercase **U** that should be lowercase ...so the correct format should be MyApiPick**u**pOrderIn as you can see here in the official example - https://take.ms/O3TBw
I can't create a pickup order because of that.

**Comment by Salamek** [comment]
@xmalikm well maybe would be better if you created PR with the fix in the first place...  (git diff will easly highlight this typo)...

**Comment by Salamek** [comment]
@xmalikm fixed in v1.3.1
