### ISSUE TITLE
Package() Expected 6 arguments. Found 5.

### ISSUE THREAD

**Issue by MichalSkoula** [Salamek/PplMyApi#61]
Constructor Package requires 6 mandatory arguments, the sixth being "ICityRouting $cityRouting".

But what should I put there, if I am creating Package without routing? https://github.com/Salamek/PplMyApi/blob/master/README.md#create-packages

**Comment by Salamek** [comment]
@MichalSkoula i was under impression that CityRouting was required for new label format? (that we use)
I don't have access to latest MyApi doc's so if you PLS can check (as a customer of PPL), it it is not required i will make it optional

**Comment by MichalSkoula** [comment]
Snad mohu i česky - aktuální dokumentace co nám poslal obchoďák je ze - https://1drv.ms/b/s!AoyEPGbZnge3q68uuv_Tby2PHjQcfQ?e=HpYz9X

Ještě psal tohle: "Předpokládám, že budete mít nevážené balíkové zásilky (tedy bez routovacího štítku)."

Podle mě je ted routing povinný jen pro vážené balíky. Ale ještě jsem mu pro jistotu napsal.

**Comment by MichalSkoula** [comment]
https://github.com/Salamek/PplMyApi#get-labels 
tady si myslím že je chyba v readme - pořadí parametrů sender/recipient/routing

**Comment by Salamek** [comment]
@MichalSkoula ~opraveno
