### ISSUE TITLE
Return code list is inconsistent

### ISSUE THREAD

**Issue by Salamek** [Salamek/PplMyApi#62]
See notes in https://github.com/Salamek/PplMyApi/blob/master/src/Enum/ReturnCode.php

Critical is 
https://github.com/Salamek/PplMyApi/blob/28fb964842e67588356b517074b027f17f7e67b5/src/Enum/ReturnCode.php#L65

Where in PDF DOC on page 38 section CreatePackages there is duplicate ID for return code 1054

**Comment by Salamek** [comment]
@jfnukal Tohle je problem dokumentace duplicitni ID pro return code 1054 strana 38

**Comment by MichalSkoula** [comment]
oficiální odpověď od PPL:

> Dobrý den,
> Děkuji za upozornění
> Hodnotu nepoužívejte

**Comment by Salamek** [comment]
No to je odpoved "jak pojd na me z boku" :D lol

**Comment by jfnukal** [comment]
Dobry den,
 jiz jsem tu kdysi psal. Mel byste oficialne kontaktovat PPL s pozadavkem na schvaleni/autorizovani Vaseho reseni. Neni autorizovano a jiz v minulosti jsme se setkali s problemy, ktere vznikly diky nepresnostem v implementacích.

Pro chod myAPI NENI stezejni, zda je nebo neni v dokumentaci chyba 1054 2x a nikdo ze zakazniku, ci 3 stran neprenasi ciselnik  tak jako vy. Je to zbytecne (byt me se to osobne u vas libi). 

Odpoved kolegy jsem tedy nevidel, ale mela byt, ze 1054 je duplicitni a spravny vyznam je: 

Insurance price must be lower or equal to „limit max částka připojištění“

Ten druhy tam nemá být.
(díky za upozornění)

Hezky den

**Comment by Salamek** [comment]
@jfnukal 

> Jiz jsem tu kdysi psal. Mel byste oficialne kontaktovat PPL s pozadavkem na schvaleni/autorizovani Vaseho reseni. Neni autorizovano a jiz v minulosti jsme se setkali s problemy, ktere vznikly diky nepresnostem v implementacích.

Muzete mi prosim vysvetlit co si predstavujete pod ` kontaktovat PPL s pozadavkem na schvaleni/autorizovani Vaseho reseni`?
nemam totiz moc predstavu o co by se melo jednat (jak toto uchopit)? A jak by neco takoveho mohlo pomoci tomuto projektu? Nejaka blizsi spoluprace s PPL by byla vitana, ale mel jsem vzdy pocit ze "mic" je na strane "velke korporace" ktere tento Open Source projekt (ktery je spravovan bez jakekoliv financni ci jine podpory) ~ulehcuje zivot jejich firemnich zakazniku :smiling_face_with_tear: 

> Pro chod myAPI NENI stezejni, zda je nebo neni v dokumentaci chyba 1054 2x a nikdo ze zakazniku, ci 3 stran neprenasi ciselnik tak jako vy. Je to zbytecne (byt me se to osobne u vas libi).

Stezejni to samozrejme neni pro omezenou/castecnou implementaci, ale tento projekt se snazi byt plnotucnym klientem pro MyApi tzn by mel implementovat ~vse. Hlavne mit ciselnik navratovych kodu je velmi uzitecna vec kdyz by nekdo porovnaval return code zlepsuje to citelnost kodu:

```php
if ($response['code'] == 1054) {
    // ....
}

// VS

if ($response['code'] == ReturnCode::INSURANCE_PRICE_MUST_BE_LOWER_OR_EQUAL_TO) {
    // ....
}
```

> Odpoved kolegy jsem tedy nevidel, ale mela byt, ze 1054 je duplicitni a spravny vyznam je:
> Insurance price must be lower or equal to „limit max částka připojištění“
> Ten druhy tam nemá být.

Dekuji za vysvetleni, to uz dava mnohem vetsi smysl.

Kdyz uz vas tu mam tak jen dotaz, kdyz se divam do vaseho DOC tak jsem si nemohl nevsimnout ze return code ciselna rada je unikatni pro cele API (coz je OK) ale vyznamy/popisy v DOC jsou duplicitni pro ruzne return kody viz komentare v https://github.com/Salamek/PplMyApi/blob/master/src/Enum/ReturnCode.php
 vypada to pak nekonzistentne a zpusobuje to trochu zmatek... napr. jaky je rozdil mezi 1035 a 1024 kdyz vyznam v doc je stejny... (tento problem je u vsech duplicit)

Jeste jednou dekuji za info
a mejte pekny den (vecer)

**Comment by Salamek** [comment]
This project wont be developed any more due to its deprecation
