### ISSUE TITLE
Chybějící povinné pole v CreatePackages

### ISSUE THREAD

**Issue by MichalSkoula** [Salamek/PplMyApi#63]
Obchoďák stále není spokojen a vymýšlí hlouposti v metode CreatePackages chybí tyto věci:

`<Flags>
<MyApiFlag>
<Code>SL</Code>
<Value>1</Value>
</MyApiFlag>
</Flags>`

Dále vícekusé balíky - i když balík není vícekusý a nebudeme je používat, podle dokumentace je to pole povinné: PackageSet a  MasterPackNumber

**Comment by MichalSkoula** [comment]
Omlouvám se, Flags jsem přehlédl.

Takže se to týká jen MasterPackNumber, nové pole povinné od 21.8.2021 podle dokumentace

**Comment by Salamek** [comment]
@MichalSkoula hmm mam to implementovane, ale nez to releasnu mam jeden dotaz, chapu to spravne ze `PackageSet` je povinny v zasilanych datech jen kdyz mam vice baliku? 

(V example datech v doc je PackageSet vynechan, ale byl bych rad kdyby to potvrdil nekdo z PPL)

Pokud to tak je tak bych z `PackageSet` udelal novou tridu protoze mit `$masterPackageNumber`, `$packagePosition` a `$packageCount` v `Package` zacina byt trochu divne :D

**Comment by Salamek** [comment]
No vlastne posilat tohle je trochu divne:

```php
'PackageSet' => [
      'MasterPackNumber' => null // Je null ok? nebo tam ma byt cislo toho jednoho baliku?
      'PackageInSetNr' =>1,
      'PackagesInSet' => 1
  ],
```

**Comment by Salamek** [comment]
@MichalSkoula `MasterPackNumber` ma byt cislo hlavniho baliku v sade baliku, jde mi o to co tam posilat kdyz se jedna jen o jeden balik, pripadne zda li muzu cele info v pripade jednoho baliku vynechat a pouzit jen 
```php
'PackageSet' => null
```

samozrejme na stitky musim dat `1/1`  atp.

**Comment by Salamek** [comment]
@MichalSkoula a jestli te muzu poprosit jestli se muzes zeptat nekoho v PPL na tohle?
https://github.com/Salamek/PplMyApi/issues/62

Na strane 38 dokumentace je duplicitni return code a ostatni return cody v rade jsou asi spatne...

**Comment by MichalSkoula** [comment]
napsal jsem jim

**Comment by Salamek** [comment]
@MichalSkoula takze masterPackageNumber == PackageNumber ok

**Comment by Salamek** [comment]
@MichalSkoula implementovano v https://github.com/Salamek/PplMyApi/releases/tag/2.2

**Comment by MichalSkoula** [comment]
po upgradu dostávám tento error

```
An uncaught Exception was encountered

Type: ParseError

Message: syntax error, unexpected ')', expecting variable (T_VARIABLE)

Filename: /var/www/html/vendor/salamek/ppl-my-api/src/Model/Package.php

Line Number: 105
```

**Comment by Salamek** [comment]
@MichalSkoula jo uz to vidim, je tam carka na vic ktera neni problem v PHP 8.1 co mam na localu ale je problem v 7.4

**Comment by MichalSkoula** [comment]
perfekt, díky
