### ISSUE TITLE
Parcelshopy a číselné řady

### ISSUE THREAD

**Issue by MichalSkoula** [Salamek/PplMyApi#66]
Když si pomocí Tools::generatePackageNumber chci vygenerovat package number pro parcelshop (product type 46/47) tak dostanu exception Unknown packageProductType

V Enum/Product jsou to konstanty PPL_PARCEL_CZ_SMART a PPL_PARCEL_CZ_SMART_COD

Jinak pro parcelshopy jsme dostali číselnou řadu 71200042447 a pro dobírku 71280086080 (podle dokumenatce 8 a 9 znamená dobírku ... tady je zrovna ten případ kdy tam místo 9 dají 8 a pro nedobírku 0)

**Comment by MichalSkoula** [comment]
A jinak dotaz, co mám ještě pro parcelshopy udělat jinak? Akorát tam dát jinou adresu?

**Comment by Salamek** [comment]
Ahoj, upravil jsem generatePackageNumber aby to pro tebe fungovalo, ale pokud nedelas s ciselnymi radami nejake pokrocilejsi manipulace tak spis doporucuji jen iterovat mezi rozsahem co ti poskytuje PPL a rvat to primo do `Package` jako string...

A co se tyce parcel shopu, tak nemam  moc poneti, podle me to bude jen zmena produktu a vyplneni infa o parcelshopu (coz asi bude adresa v `Recipient` ?

**Comment by Salamek** [comment]
Mozna $specialDelivery parameter v Package? tam jsou nejake parcel shop promene...

**Comment by MichalSkoula** [comment]
tady se vloudila chybka, viz komentář - https://github.com/Salamek/PplMyApi/commit/6b86ca8ca68b1d50660cc03bbdd5d4a95370bd9f#r68494845

**Comment by Salamek** [comment]
@MichalSkoula opraveno v 2.3.1
