### ISSUE TITLE
Parcelshop a pořadí dat na štítku

### ISSUE THREAD

**Issue by MichalSkoula** [Salamek/PplMyApi#67]
Tak pan obchoďák nám to zase nechce uznat...vadí mu, že označení parcelshopu (name2) máme dole u telefonního čísla. Má být pod jménem příjemce.

**Comment by MichalSkoula** [comment]
![ppl parcelshop](https://user-images.githubusercontent.com/5922575/157258308-dadd3169-c033-4916-abdb-460690681308.png)

já si to upravil takhle (neumím dělat pull requesty :D )

PdfLabel.php řádky 314-334:

```
$pdf->SetFont(self::$fontFamily, 'B', 10);
$x = 58.5 + $xPositionOffset;
$y = 11 + $yPositionOffset;
if ($package->getRecipient()->getName()) {
    $pdf->Text($x, $y + 2, $package->getRecipient()->getName());
}
$pdf->Text($x, $y + 7, $package->getRecipient()->getName2());

$pdf->Text($x, $y + 12, $package->getRecipient()->getContact());
$pdf->Text($x, $y + 17, $package->getRecipient()->getStreet());
$pdf->Text($x, $y + 22, sprintf('%s', $package->getRecipient()->getCity()));

$pdf->SetFont(self::$fontFamily, 'B', 20);
$pdf->Text($x, $y + 27, $package->getRecipient()->getZipCode());

$pdf->SetFont(self::$fontFamily, '', 20);
$pdf->MultiCell(15, 9, $package->getRecipient()->getCountry(), ['LTRB' => ['width' => 0.2]], 'C', 0, 0, 119.5 + $xPositionOffset, 45.3 + $yPositionOffset, true, 0, false, true, 0);

$pdf->SetFont(self::$fontFamily, '', 7);

$pdf->Text($x, $y + 39.5, sprintf('Tel.: %s', $package->getRecipient()->getPhone()));
```

**Comment by Salamek** [comment]
No tohle zatim necham lezet, ted nemam moc prostor se tomu venovat, cca za tyden na to mrknu at je to vyrsene primo v knihovne...

**Comment by MichalSkoula** [comment]
achjo, a na tom screenshotu je to naopak - vlevo jsou mé úpravy

hele klidně to zavři :))

**Comment by MichalSkoula** [comment]
commenty jsem smazal, už je to dlouho a já píšu blbiny

v podstatě ten horní obrázek to vysvětluje - takto to chtěl náš obchoďák, jiným je to třeba jedno

klidně můžeš zavřít

**Comment by Salamek** [comment]
This project wont be developed any more due to its deprecation

**Comment by MichalSkoula** [comment]
RIP a díky za něj
