### ISSUE TITLE
Vlastní $storage chybka

### ISSUE THREAD

**Issue by MichalSkoula** [Salamek/PplMyApi#70]
Pokud použiji vlastní $storage při inicializaci Api (abych mohl pracovat s více auth tokeny - více userů), tak mi tam knihovna na konec přidá /Api a pak dostanu tuhle chybu...

`Message: file_put_contents(/tmp/PPL_2/Api): failed to open stream: No such file or directory`

Řešením je buď odstanit to přidávání /Api nebo změnit lomítko, obojí funguje:

![obrazek](https://user-images.githubusercontent.com/5922575/193014953-a17cb786-ff72-48ca-bb81-de67c461fcf0.png)

**Comment by Salamek** [comment]
https://github.com/Salamek/PplMyApi/blob/d0a7c27796eba893ba3994b13e458999f13d950f/src/Api.php#L116

Vlastni $storage je slozka, ne soubor, takze si musis tu slozku prvne vytvorit:

```php
$myOwnStorage = sys_get_temp_dir() . '/my-storage';
if (!is_dir($myOwnStorage)) {
    mkdir($myOwnStorage);
}

$api = new Api(...., storage: $myOwnStorage);

```

**Comment by Salamek** [comment]
No pokud to nejak vadi, nevidim duvod pro by to nemohla byt cesta k souboru...

**Comment by Salamek** [comment]
@MichalSkoula ping

**Comment by MichalSkoula** [comment]
Já měl problém s obráceným lomítkem, což nefungovalo na linuxu, takže jsem si to naprasáka upravil takhle:

![obrazek](https://user-images.githubusercontent.com/5922575/207150968-65ce54eb-becb-489b-b5da-b39e9cae2560.png)

Koukám, že nyní už je to opraveno. Zavírám, díky.

**Comment by MichalSkoula** [comment]
předchozí comment jsem smazal, už jsem pochopil jak jsi to myslel
