### ISSUE TITLE
Incorrect WeightedPackageInfo parameter name

### ISSUE THREAD

**Issue by david-vaclavek** [Salamek/PplMyApi#71]
I'm using v1.3.3 for project compatibility reasons (can't use the newest version, don't have the PHP v7 support), anyway as a browse the code, the problem occurs in the newest version as well.

In `Api.php` file on line 475, key name should be `WeightedPackageInfo` instead of `WeightedPackageInfoIn`. I've checked it against the current WSDL version.

Currently, the `WeightedPackageInfo` is not sent to API at all.
When I changed it manually in my project, it worked.

Would it be possible to update the file?

Thank you.

**Comment by Salamek** [comment]
That means that wsdl spec was changed... PR's are welcomed!

**Comment by david-vaclavek** [comment]
Thanks.

I know anything under v7 is dead, but I'm just partly contributing to a project and I won't be able to persuade the owner to migrate.

Are you planning to release a patch for the package with v5 support?
Or should I make a PR?

**Comment by Salamek** [comment]
You are still using 1.3.3? That is still working?
So if i will branch of 1.3.3 and release 1.3.4 will that be ok for you?

**Comment by Salamek** [comment]
Hmm or composer supports branches, so maybe PHP5 branch?

**Comment by Salamek** [comment]
Yeah, i have created a PHP5 branch that is 1.3.3 with this fix, in composer.json just change version string from v1.3.3 to dev-PHP5... that should work

**Comment by david-vaclavek** [comment]
Really appreciated.

Thank you for doing that!

PS: Yes, generally PHP v5 version still works well.
