### ISSUE TITLE
DepoCode need update request

### ISSUE THREAD

**Issue by dariuszrup** [Salamek/PplMyApi#72]
DepoCode need update request. Currently the system only supports ranges 1 to 24. Request to add support for the following: 41, 44, 46, 48, 61, 62, 65, 66, 67, 96, 98, T2 or rework the setDepoCode method so that it does not throw exception

**Comment by Salamek** [comment]
@dariuszrup is there any official source for these depo codes?

**Comment by dariuszrup** [comment]
Yes, please see what official information I got from PPL:

"From the error I think that there is trouble with wrong mapping of depocodes. I see that there is used part of basic code from GitHub developer Salamek. This person is doing theyr own solution which is not approved from PPL and theyr solution has some errors. This looks like one of them. 

Salamek has own script for label creating and this error reflect incomplete list of depo codes, because we are depoCode with values which is written but there are missing another one like 41, 44, 46, 48, 61, 62, 65, 66, 67, 96, 98, T2

In this case there is need to do some modification of code, or add depots for list. I'm sorry but I don't know where and what to do because this is not our product and person Salamek is not cooperate with our company.

Thank you for your understanding"

**Comment by dariuszrup** [comment]
Oki thank you for your reply. I can prepare a proposal to fix the code tomorrow

**Comment by dariuszrup** [comment]
oki I see you already added the fix -> thanks
