### ISSUE TITLE
return type

### ISSUE THREAD

**Issue by ne2d** [Salamek/PplMyApi#79]
https://github.com/Salamek/PplMyApi/blob/812b3c3b4d2a8b6f44abf26ad9826d3ced40fe0f/src/Api.php#L173

na konci mas :array ... kdyz to u sebe zmenim na :mixed tak mi to funguje, jinak to vraci chybu Return value must be of type array, stdClass returned

**Comment by Salamek** [comment]
Fixed in 2.7.1
