### ISSUE TITLE
Margins in pdf file

### ISSUE THREAD

**Issue by AndriyFil** [Salamek/PplMyApi#83]
### Discussed in https://github.com/Salamek/PplMyApi/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **AndriyFil** February 12, 2024</sup>
Hi, I have small bug when for the barcode we need  more space, I've changed these values making less at 1 point and it seems better, could u check it and implement to your library?
<img width="756" alt="image" src="https://github.com/Salamek/PplMyApi/assets/36197959/b72e5bd8-b835-4e89-b941-ae2b2f5f9c42">

Before:
<img width="605" alt="image" src="https://github.com/Salamek/PplMyApi/assets/36197959/4357435a-af04-4fe7-a088-8f2bcd57abc1">

After:
<img width="587" alt="image" src="https://github.com/Salamek/PplMyApi/assets/36197959/7aa90eb2-0226-4638-a01d-08ecc6ef21a9">

</div>

**Comment by Salamek** [comment]
Why wont you just make a PR?

**Comment by AndriyFil** [comment]
sorry, Yes u are right, I will do in a while

**Comment by AndriyFil** [comment]
haven't done this before so I'm confused :)

**Comment by Salamek** [comment]
Solved by #84 and released in PplMyApi 2.7.3
